name: check

on:
  push:
    paths:
      - '**.go'
      - 'go.*'
      - '_fixture/**'
      - '.github/**'
      - 'codecov.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install Dependencies
        run: go install golang.org/x/lint/golint@latest

      - name: Run Tests
        run: |
          golint -set_exit_status ./...
          go test -race --coverprofile=coverage.coverprofile --covermode=atomic ./...

      - name: Upload coverage to Codecov
        if: success() && matrix.go == 1.18 && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.coverprofile
          fail_ci_if_error: false

  benchmark:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code (Previous)
        uses: actions/checkout@v3
        with:
          path: previous

      - name: Checkout Code (New)
        uses: actions/checkout@v3
        with:
          path: new

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install Dependencies
        run: go install golang.org/x/perf/cmd/benchstat@latest

      - name: Run Benchmark (Previous)
        run: |
          cd previous
          go test -run="-" -bench=".*" -count=8 ./... > benchmark.txt

      - name: Run Benchmark (New)
        run: |
          cd new
          go test -run="-" -bench=".*" -count=8 ./... > benchmark.txt

      - name: Run Benchstat
        run: |
          benchstat previous/benchmark.txt new/benchmark.txt